"""UAT report tool handler for MCP server.

Generates stakeholder-facing UAT reports from CI data and posts
them to both the Jira ticket and the GitHub PR.
"""

import json
import logging
import re
from typing import Any

from ...auth.manager import AuthManager
from ...clients.databricks_client import DatabricksMetadataClient
from ...clients.github_client import GitHubClient
from ...clients.jira_client import JiraClient, build_adf_document
from ...config import get_settings

logger = logging.getLogger(__name__)

UAT_REPORT_MARKER = "<!-- uat-report -->"


def _extract_ticket_key(pr_title: str, pr_branch: str, project_key: str = "AENG") -> str | None:
    """Extract Jira ticket key from PR title or branch name."""
    pattern = rf"({re.escape(project_key)}-\d+)"
    match = re.search(pattern, f"{pr_title} {pr_branch}", re.IGNORECASE)
    return match.group(1).upper() if match else None


async def handle_uat_report_tool(
    name: str,
    arguments: dict[str, Any],
    progress_cb: Any | None = None,
) -> dict[str, Any]:
    """Handle a UAT report tool call.

    Args:
        name: Tool name.
        arguments: Tool arguments.
        progress_cb: Optional callback for progress notifications.

    Returns:
        Tool result.
    """
    settings = get_settings()

    if not settings.github_token:
        raise RuntimeError("GitHub token not configured")

    owner = arguments["owner"]
    repo = arguments["repo"]
    pr_number = arguments["pr_number"]
    description = arguments["description"]
    queries = arguments.get("queries", [])
    jira_ticket_key = arguments.get("jira_ticket_key")
    allowed_prod_tables = arguments.get("allowed_prod_tables")

    return await generate_uat_report(
        owner=owner,
        repo=repo,
        pr_number=pr_number,
        description=description,
        queries=queries,
        jira_ticket_key=jira_ticket_key,
        github_token=settings.github_token,
        allowed_prod_tables=allowed_prod_tables,
        progress_cb=progress_cb,
    )


def _format_value(v: Any) -> str:
    """Format a query result value for display."""
    if v is None:
        return "NULL"
    if isinstance(v, float):
        if v == int(v):
            return f"{int(v):,}"
        return f"{v:,.1f}"
    if isinstance(v, int):
        return f"{v:,}"
    return str(v)


def _format_markdown_report(
    description: str,
    query_results: list[dict[str, Any]],
    pr_number: int,
    jira_ticket_key: str | None,
) -> str:
    """Format query results as a GitHub Markdown report.

    Args:
        description: Report description/context.
        query_results: List of {label, columns, rows} dicts.
        pr_number: PR number.
        jira_ticket_key: Jira ticket key if available.

    Returns:
        Markdown string.
    """
    lines = [
        UAT_REPORT_MARKER,
        "## UAT Data Impact Report",
        "",
        f"**PR #{pr_number}**"
        + (f" | **{jira_ticket_key}**" if jira_ticket_key else ""),
        "",
        f"> {description}",
        "",
    ]

    for result in query_results:
        label = result.get("label", "Query Result")
        columns = result.get("columns", [])
        rows = result.get("rows", [])
        error = result.get("error")

        lines.append(f"### {label}")
        lines.append("")

        if error:
            lines.append(f"**Error:** {error}")
            lines.append("")
            continue

        if not rows:
            lines.append("_No results_")
            lines.append("")
            continue

        # Build markdown table
        header = "| " + " | ".join(columns) + " |"
        separator = "| " + " | ".join("---" for _ in columns) + " |"
        lines.append(header)
        lines.append(separator)
        for row in rows:
            line = "| " + " | ".join(_format_value(v) for v in row) + " |"
            lines.append(line)
        lines.append("")

    lines.append("---")
    lines.append(":robot: Generated by jirade UAT Report")
    return "\n".join(lines)


def _format_adf_report(
    description: str,
    query_results: list[dict[str, Any]],
    pr_number: int,
    jira_ticket_key: str | None,
) -> dict:
    """Format query results as a Jira ADF document.

    Args:
        description: Report description/context.
        query_results: List of {label, columns, rows} dicts.
        pr_number: PR number.
        jira_ticket_key: Jira ticket key if available.

    Returns:
        ADF document dict.
    """
    sections: list[dict] = [
        {"type": "heading", "level": 2, "text": "UAT Data Impact Report"},
        {
            "type": "paragraph",
            "text": f"PR #{pr_number}"
            + (f" | {jira_ticket_key}" if jira_ticket_key else ""),
        },
        {"type": "paragraph", "text": description},
        {"type": "rule"},
    ]

    for result in query_results:
        label = result.get("label", "Query Result")
        columns = result.get("columns", [])
        rows = result.get("rows", [])
        error = result.get("error")

        sections.append({"type": "heading", "level": 3, "text": label})

        if error:
            sections.append({"type": "paragraph", "text": f"Error: {error}"})
            continue

        if not rows:
            sections.append({"type": "paragraph", "text": "No results"})
            continue

        sections.append({
            "type": "table",
            "headers": columns,
            "rows": [[_format_value(v) for v in row] for row in rows],
        })

    sections.append({"type": "rule"})
    sections.append({"type": "paragraph", "text": "Generated by jirade UAT Report"})

    return build_adf_document(sections)


async def generate_uat_report(
    owner: str,
    repo: str,
    pr_number: int,
    description: str,
    queries: list[dict[str, Any]],
    jira_ticket_key: str | None,
    github_token: str,
    allowed_prod_tables: list[str] | None = None,
    progress_cb: Any | None = None,
) -> dict[str, Any]:
    """Generate and post a UAT report.

    Args:
        owner: Repository owner.
        repo: Repository name.
        pr_number: PR number.
        description: Report description/context for stakeholders.
        queries: List of query dicts, each with:
            - "label": Display label for the result section
            - "sql": SQL query to execute (can reference CI tables and allowed prod tables)
        jira_ticket_key: Jira ticket key (auto-detected from PR if not provided).
        github_token: GitHub access token.
        allowed_prod_tables: Production tables the queries are allowed to reference
            for before/after comparisons (e.g., ['reverse_etl.salesforce.contacts']).
        progress_cb: Optional callback for progress notifications.

    Returns:
        Result dict with report content and posting status.
    """
    settings = get_settings()

    if not queries:
        return {
            "success": False,
            "error": "No queries provided. Supply a list of {label, sql} dicts.",
        }

    # Get PR info for ticket key extraction
    gh_client = GitHubClient(token=github_token, owner=owner, repo=repo)

    try:
        if not jira_ticket_key:
            if progress_cb:
                await progress_cb(0.1, None, "Extracting ticket key from PR...")
            pr = await gh_client.get_pull_request(pr_number)
            pr_title = pr.get("title", "")
            pr_branch = pr.get("head", {}).get("ref", "")
            jira_ticket_key = _extract_ticket_key(pr_title, pr_branch)
    except Exception as e:
        logger.warning(f"Failed to get PR info for ticket extraction: {e}")

    # Build CI schema prefix for security validation
    ci_schema_prefix = f"{settings.databricks_ci_catalog}.jirade_ci_{pr_number}_"

    # Execute queries
    if progress_cb:
        await progress_cb(0.2, None, f"Executing {len(queries)} analytical queries...")

    query_results = []
    with DatabricksMetadataClient(
        host=settings.databricks_host,
        http_path=settings.databricks_http_path,
        auth_type=settings.databricks_auth_type,
        token=settings.databricks_token if settings.databricks_auth_type == "token" else None,
        catalog=settings.databricks_ci_catalog,
    ) as db_client:
        for i, q in enumerate(queries):
            label = q.get("label", f"Query {i + 1}")
            sql = q.get("sql", "")

            if not sql:
                query_results.append({"label": label, "columns": [], "rows": [], "error": "Empty SQL"})
                continue

            try:
                rows = db_client.execute_analytical_query(
                    query=sql,
                    ci_schema_prefix=ci_schema_prefix,
                    allowed_prod_tables=allowed_prod_tables,
                )
                if rows:
                    columns = list(rows[0].keys())
                    data_rows = [list(row.values()) for row in rows]
                else:
                    columns = []
                    data_rows = []

                query_results.append({
                    "label": label,
                    "columns": columns,
                    "rows": data_rows,
                })
            except Exception as e:
                logger.error(f"Query '{label}' failed: {e}")
                query_results.append({
                    "label": label,
                    "columns": [],
                    "rows": [],
                    "error": str(e),
                })

            if progress_cb:
                pct = 0.2 + 0.5 * (i + 1) / len(queries)
                await progress_cb(pct, None, f"Executed query {i + 1}/{len(queries)}: {label}")

    # Format reports
    if progress_cb:
        await progress_cb(0.75, None, "Formatting reports...")

    markdown_report = _format_markdown_report(description, query_results, pr_number, jira_ticket_key)
    adf_report = _format_adf_report(description, query_results, pr_number, jira_ticket_key)

    # Post to GitHub PR
    posted_to_pr = False
    try:
        if progress_cb:
            await progress_cb(0.8, None, "Posting to GitHub PR...")
        await gh_client.upsert_pr_comment(
            pr_number=pr_number,
            body=markdown_report,
            marker=UAT_REPORT_MARKER,
        )
        posted_to_pr = True
        logger.info(f"Posted UAT report to PR #{pr_number}")
    except Exception as e:
        logger.error(f"Failed to post UAT report to PR: {e}")
    finally:
        await gh_client.close()

    # Post to Jira ticket
    posted_to_jira = False
    if jira_ticket_key:
        try:
            if progress_cb:
                await progress_cb(0.9, None, f"Posting to Jira {jira_ticket_key}...")
            auth = AuthManager(settings)
            if auth.jira.is_authenticated():
                access_token = auth.jira.get_access_token()
                cloud_id = auth.jira.get_cloud_id()
                if access_token and cloud_id:
                    jira_client = JiraClient(cloud_id=cloud_id, access_token=access_token)
                    try:
                        await jira_client.add_comment(
                            jira_ticket_key,
                            json.dumps(adf_report),
                        )
                        posted_to_jira = True
                        logger.info(f"Posted UAT report to Jira {jira_ticket_key}")
                    finally:
                        await jira_client.close()
        except Exception as e:
            logger.error(f"Failed to post UAT report to Jira: {e}")

    if progress_cb:
        await progress_cb(1.0, 1.0, "UAT report complete")

    return {
        "success": True,
        "query_count": len(queries),
        "queries_succeeded": sum(1 for r in query_results if "error" not in r),
        "queries_failed": sum(1 for r in query_results if "error" in r),
        "posted_to_pr": posted_to_pr,
        "posted_to_jira": posted_to_jira,
        "jira_ticket_key": jira_ticket_key,
        "report": markdown_report,
        "query_results": query_results,
    }
